from enum import Enum


class OTAState(Enum):
    AVAILABLE = "AVAILABLE"
    DOWNLOADING = "DOWNLOADING"

    PAUSED_LOW_BATTERY = "PAUSED_LOW_BATTERY"

    RESUMING = "RESUMING"

    VERIFYING = "VERIFYING"
    INSTALLING = "INSTALLING"
    REBOOTING = "REBOOTING"

    SUCCESS = "SUCCESS"

    FAILED = "FAILED"
    ROLLED_BACK = "ROLLED_BACK"